<?php

$language = "sr";

?>

<!DOCTYPE html>
<html lang="sr">
<head>
	<?php include "../../includes/head-elements.php"; ?>
    <title>Godisnji Izveštaj o radu 2017/18| Klub Unesco Beograd</title>
	<link rel="stylesheet" href="css/program-works.css">
</head>
<body>
	<?php include "../../includes/header.php"; ?>
	<main>
		<div class="container-program-works">
			<div class="container">
				<div class="row">
					<div class="col-xl-8">
						<div class="program-works-content">
							<h1>Godisnji Izveštaj o radu 2017/18</h1>
							<div class="contents">
								<h2>IZVEŠTAJ O RELIZACIJI PROGRAMA ZA ŠKOLSKU 2017/2018 GODINU</h2>
								<p>Kao i svake godine, Federacija UNESKO klubova Srbije – UNESKO klub Beograd upoznaje članove kao i širu javnost o rezultatima rada klubova u toku šk. 2017/18.god. a na osnovu prispelih izveštaja svakog kluba pojedinačno i opšteg uvida o radu.</p>
								<p>Na osnovu predloženog programa rada za proteklu šk. god. odvijale su se uglavnom sve aktivnosti UNESKO klubova, kao što je bilo i onih koje su klubovi samoinicijativno osmislili i realizovali, a sve u skladu sa smernicama UNESKA.</p>
								<p>Slobodni smo da konstatujemo da je veliki broj klubova vrlo nadahnuto i odgovorno angažovao mlade u  realizaciji programa rada, uz nesebično angažovanje koordinatora za Unesko klubove kao i Uprave škola.</p>
								<p>Nakon detaljne analize prispelih izveštaja UNESKO klubova o aktivnostima tokom protekle školske godine, možemo  u sažetom obliku da izdvojimo sledeće zajedničke aktivnosti:</p>
								<ul>
									<li>Obeležavanje značajnih datuma UNESKA i Ujedinjenih Nacija.</li>
									<li>Poseta muzeja, pozorišnih predstava, koncerata, izložbi, predavanja, sajma knjiga i festivala.</li>
									<li>Upoznavanje svog kraja i svoje zemlje sa osvrtom na materijalno i nematerijalno kulturno nasleđe.</li>
									<li>Upoznavanje drugih kultura i civilizacija preko studijskih putovanja po Evropi i upoznavanja spomenika kulture pod zaštitom UNESKA.</li>
									<li>Organizovanje predavanja i diskusije iz različitih oblasti kao što su oblast kulture, nauke, tolerancije, zaštite životne sredine.</li>
									<li>Promocija humanih vrednosti.</li>
									<li>Značaj fizičke aktivnosti i pravilne ishrane.</li>
									<li>Uređivanje FB stranice .</li>
									<li>Negovanje ćirilice i lepog pisanja.</li>
								</ul>
								<p>Pristigao je veliki broj detaljnih pojedinačnih izveštaja koordinatora za Unesko klubove, tako da ćemo pokušati  da izdvojimo značajnije aktivnosti za pojedine Unesko klubove.</p>
								<p><b>Šesta beogradska gimnazija </b>bila je domaćin Regionalnog susreta gimnazija iz bivše SFRJ na temu” Muzika za novi početak”, kojom prilikom je obeležen prigodnom izložbom i Dan zaštite ozonskog omotača. U cilju upoznavanja sa kulturnom baštinom svoje zemlje kao i zemalja  srednje Evrope, organizovane su sledeće aktivnosti: ” Beograd sa reka”, obilazak Dvorskog kompleksa u Beogradu, Resavska pećina, manastir Manasija. Organizovano je studijsko putovanje Budimpešta, Bratislava, Beč sa obilaskom spomenika pod zaštitom UNESKA, u cilju upoznavanja sa drugim kulturama i civilizacijama. Učestvovali su u međunarodnoj akciji ”Geografski diktant” koja ima za cilj upoznavanje  ruske kulture i civilizacije. Učestvovali su i na Drugoj konferenciji o vršnjačkom nasilju u Domu omladine Beograd. Učenik Dimitrije Petrović je bio delegiran od strane škole da učestvuje u radu Letnjeg univerziteta u Bukureštu na temu Svetska kulturna baština uz podršku Evropske federacije UNESKO klubova i Federacije UNESKO klubova Srbije.</p>
								<p>Koordinator prof. Jasna Perić </p>
								<p><b>OŠ ” Vuk Karadžić” Zrenjanin </b>posvetila je posebnu pažnju kulturnom obrazovanju  mladih i organizovala je posete sledećim izložbama i muzejima: ”Srpsko umetničko nasleđe na Kosovu i Metohiji” u Galeriji SANU, muzej Vuka i Dositeja, “Rađanje gore” u Pokrajinskom zavodu za zaštitu prirode u Novom Sadu, predstavljena je izložba ” Kaliope Austrija, žene u društvu, kulturi i nauci” u Gradskoj biblioteci Zrenjanin, izložba u Narodnom muzeju Zrenjanin ”Dakle, Vi ste taj Uroš Predić”. Imali su više manifestacija iz oblasti sporta kao što su: ” Zrenjaninski polumaraton”, “Mali Mesijeov maraton” u Botošu, takmičenje na veslačkim ergometrima, planinarski pohod  Sopotnica – kanjon Uvca 2018.god. međunarodna rekreativna manifestacija “Zogarija – Loptarija 2018.” Između ostalih aktivnosti, poklonili su i veliku pažnju humanitarnim aktivnostima. Učestvovali su u akciji borbe protiv raka dece u okviru Dana dece obolele od raka a u organizaciji Nacionalnog udruženja roditelja, podržali su akciju ”Testiraj se na HIV, jer je važno da znaš”,” Inkluzivne igre bez granica 2018.”, posvećena je i posebna pažnja lutkarskom pozorištu.</p>
								<p>Koordinator prof. Jelena Srdanović</p>
								<p><b>Gimnazija Vrnjačka Banja </b>usmerila je svoje aktivnosti na humane vrednosti društva, razvijanju svesti o važnosti tolerancije, borbe protiv nasilja i svih vrsta diskriminacija, podršci deci sa posebnim potrebama, promociji humanih vrednosti u školi i van škole, brigu o deci, starima i ugroženima. Učestvovali su i u humanitarnoj akciji NURDORA u borbi protiv raka dece i prevenciji. U pogledu negovanja maternjeg jezika i upotrebe ćirilice kao i opšte jezičke kulture, organizovan je javni čas u Gradskoj biblioteci  u Vrnjačkoj Banji na temu Medijska (ne)pismenost kojem su prisustvovali , pored učenika i roditelji i građani. Obeležen je Dan maternjeg jezika i organizovana je debata o upotrebi ćirilice. U okviru obeležavanja Dana planete zemlje, izveden je prigodan program o očuvanju životne sredine. U cilju upoznavanja drugih kultura i civilizacija, škola se pridružila studijskom putovanju:  Putevima spomenika kulture pod zaštitom UNESKA – Strazbur, Pariz, Rems, Beč.</p>
								<p>Koordinator prof. Svetlana Magdelinić</p>
								<p><b>OŠ ”Dositej Obradović” Farkaždin </b>je posvetila pažnju uređenju školskog dvorišta u cilju ukazivanja na značaj zaštite životne sredine. Svaki učenik je doneo po jednu sadnicu cveća i prikupljali su aromatična bilja i učili kako se beru i čuvaju. U cilju negovanja nematerijalne kulturne baštine, obeležili su Dan zdrave hrane prezentovanjem tradicionalnih jela svog kraja i ukazali na zaboravljene zanate. Realizovana je radionica ”U zdravom telu, zdrav duh” kao i sportski susreti učenika. Organizovana je šetnja pored Tamiša kako bi se govorilo o važnosti boravka u prirodi u svakom godišnjem dobu. Organizovano je druženje sa pesnikom i izložba najlepših sastava učenika.</p>
								<p>Koordinator prof. Vesna Kirćanski</p>
								<p><b>Gimnazija Ivanjica </b>je posebnu i sveobuhvatnu pažnju posvetila obeležavanju značajnih datuma UNESKA i Ujedinjenih Nacija i kroz obeležavanje ovih datuma realizovala vaspitno-obrazovne ciljeve iz različitih oblasti društva i planete Zemlje. Promovisali su nauku, kreativno pisanje i negovanje muzičkog obrazovanja. Učestvovali su u studijskim putovanjima  Strazbur, Pariz, Rems, Beč – Putevima spomenika pod zaštitom UNESKA i posetili Budimpeštu sa svim njenim znamenitostima i vezom sa srpskim narodom. Posvetili su pažnju i negovanju lepog pisanja uz mentorstvo Enesa Halilovića.</p>
								<p>Koordinator dr Duško Parezanović</p>
								<p><b>Zemunska gimnazija </b>je u skladu sa godišnjim planom rada Unesko klubova Srbije i ličnim željama članova kluba, posvetila pažnju svetskoj i domaćoj kulturnoj baštini, upoznavanju spomenika pod zaštitom UNESKA. Bilo je reči o Miroslavljevom jevanđelju i o ulozi Nikole Tesle kao nezaobilaznom nematerijalnom kulturnom nasleđu. U cilju što bolje pripreme studijskog putovanja za Pariz uz obilazak Strazbura, Remsa i Beča, vršene su pripreme učesnika. Razmatrane su civilizacijske razlike u običajima Francuza, Nemaca i Rusa. Organizovan je karneval ”U susret proleću” prilikom kojeg je prikazano kako se u Italiji, Francuskoj, Nemačkoj, Americi, Rusiji pa i u Japanu kao i kod nas u Srbiji organizuju poklade i karnevali i kako se narodi pripremaju za dolazak proleća. Obeležen je i Dan Frankofonije. U aprilu je realizovano studijsko putovanje u Francusku. Cilj ovog putovanja je obilazak spomenika pod zaštitom UNESKA u Strazburu, gde su obišli i Evropski parlament i Savet Evrope, pored spomenika u starom gradu, zatim je sledio obilazak Pariza, Remsa i Beča. Pored spomenika kulture, učesnici su se upoznali i sa kulturom i običajima, hranom i ostalim raznolikostima ovih zemalja. Takođe su razvijali drugarstvo i prijateljstvo sa ostalim učesnicima.</p>
								<p>Koordinator prof. Jelena Međedović</p>
								<p><b>OŠ ”Vojislav Voka Savić” Lazarevac </b>Osnovni cilj kluba je razvijanje svesti kod učenika o poštovanju pravde, zakona, ljudskih prava i osnovnih ljudskih sloboda, bez obzira na rasu, pol i religiju. Učenici su upoznati sa idejama UNESKA koje se odnose na obrazovanje, kulturu i nauku kao i sa spomenicima kulture pod zaštitom UNESKA. Učesnici su u realizaciji studijskog putovanja za  Francusku i Beč i spomenicima kulture koje će obići. U okviru obeležavanja Frankofonije ukazano je na kulturne i civilizacijske raznolikosti ali i sličnosti. Posebno je posvećena pažnja zaštiti životne sredine i planete Zemlje i značaju čuvanja pijaće vode i njenom racionalnom trošenju.</p>
								<p>Koordinator prof. Tatjana Ćirić</p>
								<p><b>Osma beogradska gimnazija </b>je svoj rad Unesko kluba usmerila na razvijanje interesovanja mladih za čitanje knjiga u okviru posete Sajma knjiga. Organizovali su i okrugli sto na temu ”Vaspitanje dece nekad i sad” u Zavodu za vaspitanje dece i omladine. Gledali su operu Karmen u Narodnom pozorištu u Beogradu i osmislili predstavu Lepa Protina kći po tekstu pesme Đorđa Balaševića. Pored ovih posebnih aktivnosti, radili su na informisanju učenika o značaju zaštite i očuvanja kulturnih dobara kao i o samoj suštini  brige UNESKA za materijalnu i nematerijalnu kulturnu baštinu u sklopu pripreme studijskog putovanja u Francusku i Austriju.</p>
								<p>Koordinatori prof. Vesna Grubor i Slađana Ostojić</p>
								<p><b>OŠ ”Desanka Maksimović” Gornji Milanovac </b>je početkom školske godine otpočela svoje aktivnosti otvaranjem Dečije nedelje i razgovorima o pravima deteta. Posebnim programom učenika obeležili su Dan UN. Učenici su u nošnjama država koje su predstavljali i pesmama na njihovom jeziku  pokušali da približe kulturu tih zemalja. Doživljaj je upotpunjen spremanjem nacionalnih jela. Organizovane su i tribine kao što je to bila tribina pod sloganom ”Sve je moguće” povodom Dana tolerancije zatim tribina  na temu promovisanja socijalne inkluzije i prihvatanja različitosti u saradnji sa Crvenim krstom Gornjeg Milanovca i Kulturnim centrom. Gosti tribine bili su paraolimpijski šampioni koji su ostavili snažnu poruku na sve posetioce. Organizovali su i posete kulturno-istorijskim spomenicima Srbije i dolazak glumice Vesne Stanković koja je izvela dramu »Milunka Savić».</p>
								<p>Koordinator prof. Vesna Acović</p>
								<p><b>UTŠ Vrnjačka Banja</b> je uskladila svoje aktivnosti Unesko kluba u vezi sa sadržajem rada same škole. Održani su javni časovi gastronomije  u cilju prezentacije raznolikosti pripremanja hrane zemalja Evropske unije. Organizovana je i gastronomska izložba »Goût de France» i obeleženi su Dani Frankofonije. Posvećena je i posebna pažnja deci koja su ometena u razvoju kao i poeziji. Ukazivanjem na kulturne raznolikosti preko gastronomije, učenici su počeli i pripremu za Studijsko putovanje za Mađarsku i Austriju sa posetom Budimpešte i Beča. Studijsko putovanje je organizovano u cilju upoznavanja drugih  kultura i običaja kao i spomenika kulture pod zaštitom UNESKA. Obeleženo je 200 godina od izdavanja Vukovog Prvog srpskog rečnika u Gradskoj biblioteci. Federacija UNESKO klubova Srbije je delegirala dva delegata iz ove škole prof. Jovanović Ritu i prof. Bežanović Sonju da prisustvuju Vanrednom kongresu Evropske federacije UNESKO klubova, asocijacija i centara od 28.juna do 01.jula 2018.god. u Rumuniji.</p>
								<p>Koordinatori prof. Snežana Stevanović i Danijela Vasović</p>
								<p><b>UTŠ Beograd UNESKO klub “Jug Bogdan”</b> je ove godine imao vrlo lepe aktivnosti u odnosu na aktivnosti u ranijim godinama, što je za svaku pohvalu. Oni su posebnu pažnju posvetili spomenicima kulture naše zemlje kao i onih u Evropi pod zaštitom UNESKA. Obilazak Golubačke tvrđave, poseta muzeju praistorijskog lokaliteta, Smederevske tvrđave, uz osvrt na istorijski značaj i pad pod tursku vlast, Doma Jevrema Grujića – izložba slika Paje Jovanovića, Novog Sada i crkve Imena Marijinog i Saborne crkve u okviru učenja o verskoj toleranciji. U Valjevu su posetili Muzej grada Valjeva, Muslimanski konak, spomenike posečenim knezovima, Alekse Nenadovića, Ilije Birčanina, Živojina Mišića i Stevana Filipovića kao i spomenik Desanke Maksimović. U Nišu su obišli Memorijalni kompleks ”12. Februar”- logor iz Drugog svetskog rata, Ćele kulu, Narodni muzej i Nišku tvrđavu. Posetili su i Aušvic – muzej holokausta i rudnik soli “Velička” koji je na listi Svetske kulturne baštine. Imaju vrlo lepo uređenu FB stranicu.</p>
								<p>Koordinatori prof. Jelena Bjeković i Svetlana Paunović uz izuzetnu podršku učenika IV/1 i IV/3 ove škole</p>
								<p><b>Gimnazija “20.oktobar” Bačka Palanka</b> je kao i svake godine posebnu pažnju posvetila upoznavanju drugih kultura i običaja. Pisani su radovi na temu Zaštićeni verski objekti od strane UNESKA kod nas i u svetu. Svi radovi su predstavljeni učenicima ove škole i onima koji su bili zainteresovani. Bio je to obiman i kvalitetan rad učenika a i koordinatora. Odabrali su studijsko putovanje Bolonja, Rim, Tivoli, Areco. Nakon putovanja, učenici su predstavili zidni pano sa svim najznačajnijim spomenicima koje su upoznali i fotografisali. Pisani su i radovi u vezi ovog putovanja sa utiscima koje su poneli sa sobom i onim što su videli i naučili.</p>
								<p>Koordinator prof. Ilinka Ilić</p> <br>
								<p>Ovim predstavljanjem pojedinih Klubova za Unesko, nismo uspeli da predstavimo rad i ostalih Unesko klubova, u nedostatku konkretnih informacija, što ne znači da nisu imali određene aktivnosti kao n.pr.  XII beogradska gimnazija koja je uzela učešće u studijskom putovanju za Rim, OŠ »Vasa Pelagić» koja je učestvovala u studijskom putovanju za Francusku i Austriju kao i VII beogradska gimnazija, OŠ » Vladislav Ribnikar », OŠ »Siniša Nikolajević » Beograd, Gimnazija „Svetozar Marković“ Niš  i Gimnazija Smederevo.</p>
								<p>Postoje i drugi Unesko klubovi koji imaju mnogo lepih aktivnosti, ali mi nemamo naviku da sve ono što radimo pribeležimo i pokažemo javnosti, što je inače običaj i obaveza u svetu.</p>
								<p>U pogledu sadržaja aktivnosti same Federacije Unesko klubova Srbije, možemo slobodno reći da je veliki deo vremena i veliki  trud uložen u pokušaju da obezbedimo sredstva za realizaciju sledećih tema iz oblasti kulture i obrazovanja: „Nematerijalno kulturno nasleđe kao sastavni deo edukacije mladih“ koje je upućeno Ministarstvu kulture i informisanja Srbije i „Ćirilica i mladi“ koje je upućeno Sekretarijatu za kulturu grada Beograda. Sredstva koja su tražena bila su vrlo skromna ali ovi projekti nisu naišli na razumevanje o potrebi istih i na materijalnu podršku.</p>
								<p>Vršene su pripreme za Vanredni  kongres Evropske federacije Unesko klubova, Asocijacija i Centara na temu „Evropsko kulturno nasleđe, poziv na dijalog i saradnju“. Vršen je odabir delegata i izabrana su dva delegata iz Srbije, iz UTŠ Vrnjačka Banja, da prisustvuju ovom Kongresu. Zastupali su nas prof. Jovanović Rita i prof. Bežanović Sonja.</p>
								<p>Pružili smo podršku u organizovanju Letnjeg Univerziteta na temu „Kultura mira i obrazovanja za održivi razvoj“ u organizaciji Katedre za Unesko u oblasti kulture, prava čoveka i obrazovanja za održivi razvoj  „Dimitri Cantemir“ u Bukureštu. Rad Letnjeg Univerziteta je podržala Nacionalna komisija za Unesko Rumunije i Evropska federacija Unesko klubova, Asocijacija i Centara. Letnji Univerzitet se odnosio na časove, radionice, panele i okrugle stolove na teme: Kultura mira i nenasilno ponašanje, Svetska kulturna baština i obrazovanje za održivi razvoj. Izabrana su dva učenika za ovaj Letnji Univerzitet i to : Mina Milović iz Gimnazije Ivanjica i Dimitrije Petrović iz VI beogradske gimnazije.</p>
								<p>Na poziv organizatora redovnog zasedanja Svetskog i Evropskog Izvršnog odbora Gospodina Ioannis Maronitisa, Predsednik i zamenik Predsednika Federacije Unesko klubova Srbije  prisustvovali su u radu Izvršnog odbora Evropske federacije UNESKO klubova u mestu Halkida u Grčkoj u vremenu od 08-11.juna 2018 god. G-din Ioannis Maronitis je Predsednik UNESKO kluba Pireus & islands i član Izvršnog odbora Svetske Federacije UNESKO klubova, Asocijacija i Centara.</p>
								<p>Radili smo na osmišljavanju studijskih putovanja u saradnji sa Klubovima za Unesko Srbije i na realizaciji istih. Ova putovanja se organizuju pod pokroviteljstvom Evropske federacije UNESKO klubova, Asocijacija i Centara.</p>
								<p>Pored ovih aktivnosti, održavali smo kontakte sa ostalim Federacijama UNESKO klubova u Evropi u cilju usklađivanja aktivnosti i poboljšanja saradnje. Na poziv Federacije UNESKO klubova Bugarske uključili smo se u projekat negovanja nematerijalne kulturne baštine.</p>
								<p>Redovno aktivno učestvujemo u radu Izvršnog odbora Evropske Federacije Unesko klubova,  uključujući i Severnu Ameriku. Bili smo prisutni i u Yekaterinburgu u Rusiji na zasedanju Izvršnog odbora EFUCA aprila 2017.god.</p>
								<p>Na kraju ovog našeg izveštaja želim da se zahvalim svim učesnicima u radu UNESKO klubova Srbije, koji su na dobrovoljnoj osnovi a iziskuju veliki napor i požrtvovanje.</p>
								<br>
								<p>Predsednik Federacije UNESKO klubova Srbije <br>klub UNESKO Beograd<br>mr Milica Dromnjaković, prof.</p>
								<p>U Beogradu, 29.08.2018.god.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</main>
	<?php include "../../includes/footer.php"; ?>
</body>
</html> 